-- Migration 0014: seed Jan–Mar 2026 visibility history for trend charts

-- 2026-01
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('brush', 'Brush', 'pharmeasy', '2026-01-31', '2026-01', NULL);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('brush', 'Brush', 'tata_1mg', '2026-01-31', '2026-01', 35);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('brush', 'Brush', 'zepto', '2026-01-31', '2026-01', 6);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('brush', 'Brush', 'amazon_pharmacy', '2026-01-31', '2026-01', 6);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('brush', 'Gentle brush', 'pharmeasy', '2026-01-31', '2026-01', NULL);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('brush', 'Gentle brush', 'tata_1mg', '2026-01-31', '2026-01', 33);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('brush', 'Gentle brush', 'zepto', '2026-01-31', '2026-01', 9);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('brush', 'Gentle brush', 'amazon_pharmacy', '2026-01-31', '2026-01', 6);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('brush', 'Sensodyne', 'pharmeasy', '2026-01-31', '2026-01', 7);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('brush', 'Sensodyne', 'tata_1mg', '2026-01-31', '2026-01', 36);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('brush', 'Sensodyne', 'zepto', '2026-01-31', '2026-01', 5);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('brush', 'Sensodyne', 'amazon_pharmacy', '2026-01-31', '2026-01', 3);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('brush', 'Toothbrush', 'pharmeasy', '2026-01-31', '2026-01', 5);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('brush', 'Toothbrush', 'tata_1mg', '2026-01-31', '2026-01', 34);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('brush', 'Toothbrush', 'zepto', '2026-01-31', '2026-01', 7);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('brush', 'Toothbrush', 'amazon_pharmacy', '2026-01-31', '2026-01', 5);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('brush', 'sensitivity', 'pharmeasy', '2026-01-31', '2026-01', 5);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('brush', 'sensitivity', 'tata_1mg', '2026-01-31', '2026-01', 33);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('brush', 'sensitivity', 'zepto', '2026-01-31', '2026-01', 9);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('brush', 'sensitivity', 'amazon_pharmacy', '2026-01-31', '2026-01', NULL);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('paste', 'Paste', 'pharmeasy', '2026-01-31', '2026-01', 6);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('paste', 'Paste', 'tata_1mg', '2026-01-31', '2026-01', 10);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('paste', 'Paste', 'zepto', '2026-01-31', '2026-01', 10);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('paste', 'Paste', 'amazon_pharmacy', '2026-01-31', '2026-01', NULL);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('paste', 'Sensitivity', 'pharmeasy', '2026-01-31', '2026-01', 5);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('paste', 'Sensitivity', 'tata_1mg', '2026-01-31', '2026-01', 6);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('paste', 'Sensitivity', 'zepto', '2026-01-31', '2026-01', 8);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('paste', 'Sensitivity', 'amazon_pharmacy', '2026-01-31', '2026-01', 6);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('paste', 'Sensodyne', 'pharmeasy', '2026-01-31', '2026-01', 6);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('paste', 'Sensodyne', 'tata_1mg', '2026-01-31', '2026-01', 8);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('paste', 'Sensodyne', 'zepto', '2026-01-31', '2026-01', 10);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('paste', 'Sensodyne', 'amazon_pharmacy', '2026-01-31', '2026-01', 3);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('paste', 'Toothpaste', 'pharmeasy', '2026-01-31', '2026-01', 5);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('paste', 'Toothpaste', 'tata_1mg', '2026-01-31', '2026-01', 7);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('paste', 'Toothpaste', 'zepto', '2026-01-31', '2026-01', 11);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('paste', 'Toothpaste', 'amazon_pharmacy', '2026-01-31', '2026-01', 7);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('parodontax', 'Gum care', 'pharmeasy', '2026-01-31', '2026-01', 7);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('parodontax', 'Gum care', 'tata_1mg', '2026-01-31', '2026-01', 9);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('parodontax', 'Gum care', 'zepto', '2026-01-31', '2026-01', 13);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('parodontax', 'Gum care', 'amazon_pharmacy', '2026-01-31', '2026-01', 9);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('parodontax', 'Paste', 'pharmeasy', '2026-01-31', '2026-01', 6);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('parodontax', 'Paste', 'tata_1mg', '2026-01-31', '2026-01', 13);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('parodontax', 'Paste', 'zepto', '2026-01-31', '2026-01', 15);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('parodontax', 'Paste', 'amazon_pharmacy', '2026-01-31', '2026-01', 9);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('parodontax', 'Toothpaste', 'pharmeasy', '2026-01-31', '2026-01', 8);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('parodontax', 'Toothpaste', 'tata_1mg', '2026-01-31', '2026-01', 10);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('parodontax', 'Toothpaste', 'zepto', '2026-01-31', '2026-01', 17);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('parodontax', 'Toothpaste', 'amazon_pharmacy', '2026-01-31', '2026-01', 10);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('pronamel', 'paste', 'pharmeasy', '2026-01-31', '2026-01', 11);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('pronamel', 'paste', 'tata_1mg', '2026-01-31', '2026-01', 11);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('pronamel', 'paste', 'zepto', '2026-01-31', '2026-01', 17);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('pronamel', 'paste', 'amazon_pharmacy', '2026-01-31', '2026-01', 5);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('pronamel', 'pronamel', 'pharmeasy', '2026-01-31', '2026-01', 7);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('pronamel', 'pronamel', 'tata_1mg', '2026-01-31', '2026-01', 11);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('pronamel', 'pronamel', 'zepto', '2026-01-31', '2026-01', 19);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('pronamel', 'pronamel', 'amazon_pharmacy', '2026-01-31', '2026-01', 8);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('pronamel', 'sensitivity', 'pharmeasy', '2026-01-31', '2026-01', 10);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('pronamel', 'sensitivity', 'tata_1mg', '2026-01-31', '2026-01', 14);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('pronamel', 'sensitivity', 'zepto', '2026-01-31', '2026-01', 16);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('pronamel', 'sensitivity', 'amazon_pharmacy', '2026-01-31', '2026-01', 5);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('pronamel', 'sensodyne', 'pharmeasy', '2026-01-31', '2026-01', 11);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('pronamel', 'sensodyne', 'tata_1mg', '2026-01-31', '2026-01', 12);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('pronamel', 'sensodyne', 'zepto', '2026-01-31', '2026-01', 19);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('pronamel', 'sensodyne', 'amazon_pharmacy', '2026-01-31', '2026-01', 5);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('pronamel', 'toothpaste', 'pharmeasy', '2026-01-31', '2026-01', 9);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('pronamel', 'toothpaste', 'tata_1mg', '2026-01-31', '2026-01', 11);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('pronamel', 'toothpaste', 'zepto', '2026-01-31', '2026-01', 16);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('pronamel', 'toothpaste', 'amazon_pharmacy', '2026-01-31', '2026-01', 7);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('mouthwash', 'Listerine', 'pharmeasy', '2026-01-31', '2026-01', 10);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('mouthwash', 'Listerine', 'tata_1mg', '2026-01-31', '2026-01', 13);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('mouthwash', 'Listerine', 'zepto', '2026-01-31', '2026-01', 20);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('mouthwash', 'Listerine', 'amazon_pharmacy', '2026-01-31', '2026-01', 11);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('mouthwash', 'Mouthwash', 'pharmeasy', '2026-01-31', '2026-01', 10);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('mouthwash', 'Mouthwash', 'tata_1mg', '2026-01-31', '2026-01', 12);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('mouthwash', 'Mouthwash', 'zepto', '2026-01-31', '2026-01', 21);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('mouthwash', 'Mouthwash', 'amazon_pharmacy', '2026-01-31', '2026-01', 9);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('mouthwash', 'sensodyne', 'pharmeasy', '2026-01-31', '2026-01', 7);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('mouthwash', 'sensodyne', 'tata_1mg', '2026-01-31', '2026-01', 12);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('mouthwash', 'sensodyne', 'zepto', '2026-01-31', '2026-01', 22);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('mouthwash', 'sensodyne', 'amazon_pharmacy', '2026-01-31', '2026-01', 11);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('mouthwash', 'sensodyne mouthwash', 'pharmeasy', '2026-01-31', '2026-01', 7);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('mouthwash', 'sensodyne mouthwash', 'tata_1mg', '2026-01-31', '2026-01', 16);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('mouthwash', 'sensodyne mouthwash', 'zepto', '2026-01-31', '2026-01', 23);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('mouthwash', 'sensodyne mouthwash', 'amazon_pharmacy', '2026-01-31', '2026-01', 10);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('polident', 'polident', 'pharmeasy', '2026-01-31', '2026-01', 13);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('polident', 'polident', 'tata_1mg', '2026-01-31', '2026-01', 16);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('polident', 'polident', 'zepto', '2026-01-31', '2026-01', 26);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('polident', 'polident', 'amazon_pharmacy', '2026-01-31', '2026-01', 12);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('polident', 'denture adhesive', 'pharmeasy', '2026-01-31', '2026-01', 13);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('polident', 'denture adhesive', 'tata_1mg', '2026-01-31', '2026-01', 16);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('polident', 'denture adhesive', 'zepto', '2026-01-31', '2026-01', NULL);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('polident', 'denture adhesive', 'amazon_pharmacy', '2026-01-31', '2026-01', 14);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('polident', 'denture fixative cream', 'pharmeasy', '2026-01-31', '2026-01', NULL);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('polident', 'denture fixative cream', 'tata_1mg', '2026-01-31', '2026-01', 15);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('polident', 'denture fixative cream', 'zepto', '2026-01-31', '2026-01', 23);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('polident', 'denture fixative cream', 'amazon_pharmacy', '2026-01-31', '2026-01', 10);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('crocin', 'Dolo', 'pharmeasy', '2026-01-31', '2026-01', 5);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('crocin', 'Dolo', 'tata_1mg', '2026-01-31', '2026-01', 5);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('crocin', 'Dolo', 'zepto', '2026-01-31', '2026-01', 10);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('crocin', 'Dolo', 'amazon_pharmacy', '2026-01-31', '2026-01', 4);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('crocin', 'Pain Killer', 'pharmeasy', '2026-01-31', '2026-01', 6);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('crocin', 'Pain Killer', 'tata_1mg', '2026-01-31', '2026-01', 4);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('crocin', 'Pain Killer', 'zepto', '2026-01-31', '2026-01', 8);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('crocin', 'Pain Killer', 'amazon_pharmacy', '2026-01-31', '2026-01', 6);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('crocin', 'Pain Relief', 'pharmeasy', '2026-01-31', '2026-01', 3);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('crocin', 'Pain Relief', 'tata_1mg', '2026-01-31', '2026-01', NULL);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('crocin', 'Pain Relief', 'zepto', '2026-01-31', '2026-01', 8);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('crocin', 'Pain Relief', 'amazon_pharmacy', '2026-01-31', '2026-01', 3);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('crocin', 'Paracetamol', 'pharmeasy', '2026-01-31', '2026-01', 4);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('crocin', 'Paracetamol', 'tata_1mg', '2026-01-31', '2026-01', 5);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('crocin', 'Paracetamol', 'zepto', '2026-01-31', '2026-01', 8);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('crocin', 'Paracetamol', 'amazon_pharmacy', '2026-01-31', '2026-01', 3);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('crocin', 'cough syrup', 'pharmeasy', '2026-01-31', '2026-01', 7);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('crocin', 'cough syrup', 'tata_1mg', '2026-01-31', '2026-01', 8);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('crocin', 'cough syrup', 'zepto', '2026-01-31', '2026-01', 6);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('crocin', 'cough syrup', 'amazon_pharmacy', '2026-01-31', '2026-01', 4);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('iodex', 'Balm', 'pharmeasy', '2026-01-31', '2026-01', 8);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('iodex', 'Balm', 'tata_1mg', '2026-01-31', '2026-01', 11);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('iodex', 'Balm', 'zepto', '2026-01-31', '2026-01', 12);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('iodex', 'Balm', 'amazon_pharmacy', '2026-01-31', '2026-01', 7);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('iodex', 'Pain relief', 'pharmeasy', '2026-01-31', '2026-01', 8);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('iodex', 'Pain relief', 'tata_1mg', '2026-01-31', '2026-01', 12);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('iodex', 'Pain relief', 'zepto', '2026-01-31', '2026-01', 14);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('iodex', 'Pain relief', 'amazon_pharmacy', '2026-01-31', '2026-01', 6);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('iodex', 'Relief Spray', 'pharmeasy', '2026-01-31', '2026-01', 5);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('iodex', 'Relief Spray', 'tata_1mg', '2026-01-31', '2026-01', NULL);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('iodex', 'Relief Spray', 'zepto', '2026-01-31', '2026-01', NULL);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('iodex', 'Relief Spray', 'amazon_pharmacy', '2026-01-31', '2026-01', 8);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('voltaren', 'pain relief', 'pharmeasy', '2026-01-31', '2026-01', 14);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('voltaren', 'pain relief', 'tata_1mg', '2026-01-31', '2026-01', 17);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('voltaren', 'pain relief', 'zepto', '2026-01-31', '2026-01', NULL);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('voltaren', 'pain relief', 'amazon_pharmacy', '2026-01-31', '2026-01', 9);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('centrum', 'Bone Health', 'pharmeasy', '2026-01-31', '2026-01', 5);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('centrum', 'Bone Health', 'tata_1mg', '2026-01-31', '2026-01', 9);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('centrum', 'Bone Health', 'zepto', '2026-01-31', '2026-01', NULL);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('centrum', 'Bone Health', 'amazon_pharmacy', '2026-01-31', '2026-01', 4);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('centrum', 'Multivitamin', 'pharmeasy', '2026-01-31', '2026-01', 8);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('centrum', 'Multivitamin', 'tata_1mg', '2026-01-31', '2026-01', 7);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('centrum', 'Multivitamin', 'zepto', '2026-01-31', '2026-01', 10);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('centrum', 'Multivitamin', 'amazon_pharmacy', '2026-01-31', '2026-01', 6);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('centrum', 'Recharge', 'pharmeasy', '2026-01-31', '2026-01', 7);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('centrum', 'Recharge', 'tata_1mg', '2026-01-31', '2026-01', 7);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('centrum', 'Recharge', 'zepto', '2026-01-31', '2026-01', NULL);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('centrum', 'Recharge', 'amazon_pharmacy', '2026-01-31', '2026-01', 8);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('centrum', 'Vitamins', 'pharmeasy', '2026-01-31', '2026-01', NULL);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('centrum', 'Vitamins', 'tata_1mg', '2026-01-31', '2026-01', 6);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('centrum', 'Vitamins', 'zepto', '2026-01-31', '2026-01', 10);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('centrum', 'Vitamins', 'amazon_pharmacy', '2026-01-31', '2026-01', 4);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('centrum', 'calcium', 'pharmeasy', '2026-01-31', '2026-01', 6);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('centrum', 'calcium', 'tata_1mg', '2026-01-31', '2026-01', 8);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('centrum', 'calcium', 'zepto', '2026-01-31', '2026-01', 11);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('centrum', 'calcium', 'amazon_pharmacy', '2026-01-31', '2026-01', NULL);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('ostocalcium', 'Health supplement', 'pharmeasy', '2026-01-31', '2026-01', 10);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('ostocalcium', 'Health supplement', 'tata_1mg', '2026-01-31', '2026-01', 10);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('ostocalcium', 'Health supplement', 'zepto', '2026-01-31', '2026-01', 16);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('ostocalcium', 'Health supplement', 'amazon_pharmacy', '2026-01-31', '2026-01', 7);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('ostocalcium', 'Multivitamin', 'pharmeasy', '2026-01-31', '2026-01', 7);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('ostocalcium', 'Multivitamin', 'tata_1mg', '2026-01-31', '2026-01', 14);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('ostocalcium', 'Multivitamin', 'zepto', '2026-01-31', '2026-01', 17);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('ostocalcium', 'Multivitamin', 'amazon_pharmacy', '2026-01-31', '2026-01', 9);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('ostocalcium', 'Vitamin D', 'pharmeasy', '2026-01-31', '2026-01', 8);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('ostocalcium', 'Vitamin D', 'tata_1mg', '2026-01-31', '2026-01', 10);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('ostocalcium', 'Vitamin D', 'zepto', '2026-01-31', '2026-01', 18);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('ostocalcium', 'Vitamin D', 'amazon_pharmacy', '2026-01-31', '2026-01', NULL);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('ostocalcium', 'calcium', 'pharmeasy', '2026-01-31', '2026-01', 7);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('ostocalcium', 'calcium', 'tata_1mg', '2026-01-31', '2026-01', 12);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('ostocalcium', 'calcium', 'zepto', '2026-01-31', '2026-01', 18);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('ostocalcium', 'calcium', 'amazon_pharmacy', '2026-01-31', '2026-01', 10);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('ostocalcium', 'vitamins', 'pharmeasy', '2026-01-31', '2026-01', NULL);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('ostocalcium', 'vitamins', 'tata_1mg', '2026-01-31', '2026-01', 11);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('ostocalcium', 'vitamins', 'zepto', '2026-01-31', '2026-01', 17);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('ostocalcium', 'vitamins', 'amazon_pharmacy', '2026-01-31', '2026-01', 8);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('eno', 'Acidity', 'pharmeasy', '2026-01-31', '2026-01', 3);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('eno', 'Acidity', 'tata_1mg', '2026-01-31', '2026-01', 4);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('eno', 'Acidity', 'zepto', '2026-01-31', '2026-01', 6);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('eno', 'Acidity', 'amazon_pharmacy', '2026-01-31', '2026-01', 3);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('eno', 'Antacid', 'pharmeasy', '2026-01-31', '2026-01', 7);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('eno', 'Antacid', 'tata_1mg', '2026-01-31', '2026-01', 7);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('eno', 'Antacid', 'zepto', '2026-01-31', '2026-01', 6);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('eno', 'Antacid', 'amazon_pharmacy', '2026-01-31', '2026-01', 4);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('eno', 'Digestion', 'pharmeasy', '2026-01-31', '2026-01', 4);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('eno', 'Digestion', 'tata_1mg', '2026-01-31', '2026-01', 4);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('eno', 'Digestion', 'zepto', '2026-01-31', '2026-01', 7);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('eno', 'Digestion', 'amazon_pharmacy', '2026-01-31', '2026-01', 6);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('eno', 'Eno', 'pharmeasy', '2026-01-31', '2026-01', 4);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('eno', 'Eno', 'tata_1mg', '2026-01-31', '2026-01', 4);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('eno', 'Eno', 'zepto', '2026-01-31', '2026-01', 5);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('eno', 'Eno', 'amazon_pharmacy', '2026-01-31', '2026-01', 4);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('eno', 'Indigestion', 'pharmeasy', '2026-01-31', '2026-01', 6);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('eno', 'Indigestion', 'tata_1mg', '2026-01-31', '2026-01', 5);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('eno', 'Indigestion', 'zepto', '2026-01-31', '2026-01', 6);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('eno', 'Indigestion', 'amazon_pharmacy', '2026-01-31', '2026-01', 5);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('otrivin', 'blocked nose', 'pharmeasy', '2026-01-31', '2026-01', 7);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('otrivin', 'blocked nose', 'tata_1mg', '2026-01-31', '2026-01', 11);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('otrivin', 'blocked nose', 'zepto', '2026-01-31', '2026-01', 14);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('otrivin', 'blocked nose', 'amazon_pharmacy', '2026-01-31', '2026-01', 6);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('otrivin', 'nasal spray', 'pharmeasy', '2026-01-31', '2026-01', 7);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('otrivin', 'nasal spray', 'tata_1mg', '2026-01-31', '2026-01', NULL);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('otrivin', 'nasal spray', 'zepto', '2026-01-31', '2026-01', 14);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('otrivin', 'nasal spray', 'amazon_pharmacy', '2026-01-31', '2026-01', 8);

-- 2026-02
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('brush', 'Brush', 'pharmeasy', '2026-02-28', '2026-02', 6);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('brush', 'Brush', 'tata_1mg', '2026-02-28', '2026-02', 36);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('brush', 'Brush', 'zepto', '2026-02-28', '2026-02', 4);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('brush', 'Brush', 'amazon_pharmacy', '2026-02-28', '2026-02', 1);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('brush', 'Gentle brush', 'pharmeasy', '2026-02-28', '2026-02', 6);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('brush', 'Gentle brush', 'tata_1mg', '2026-02-28', '2026-02', 33);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('brush', 'Gentle brush', 'zepto', '2026-02-28', '2026-02', 4);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('brush', 'Gentle brush', 'amazon_pharmacy', '2026-02-28', '2026-02', 3);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('brush', 'Sensodyne', 'pharmeasy', '2026-02-28', '2026-02', 2);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('brush', 'Sensodyne', 'tata_1mg', '2026-02-28', '2026-02', 34);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('brush', 'Sensodyne', 'zepto', '2026-02-28', '2026-02', 7);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('brush', 'Sensodyne', 'amazon_pharmacy', '2026-02-28', '2026-02', 3);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('brush', 'Toothbrush', 'pharmeasy', '2026-02-28', '2026-02', 3);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('brush', 'Toothbrush', 'tata_1mg', '2026-02-28', '2026-02', 35);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('brush', 'Toothbrush', 'zepto', '2026-02-28', '2026-02', 5);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('brush', 'Toothbrush', 'amazon_pharmacy', '2026-02-28', '2026-02', 3);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('brush', 'sensitivity', 'pharmeasy', '2026-02-28', '2026-02', 2);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('brush', 'sensitivity', 'tata_1mg', '2026-02-28', '2026-02', 33);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('brush', 'sensitivity', 'zepto', '2026-02-28', '2026-02', 8);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('brush', 'sensitivity', 'amazon_pharmacy', '2026-02-28', '2026-02', 3);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('paste', 'Paste', 'pharmeasy', '2026-02-28', '2026-02', 6);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('paste', 'Paste', 'tata_1mg', '2026-02-28', '2026-02', 9);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('paste', 'Paste', 'zepto', '2026-02-28', '2026-02', 8);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('paste', 'Paste', 'amazon_pharmacy', '2026-02-28', '2026-02', 4);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('paste', 'Sensitivity', 'pharmeasy', '2026-02-28', '2026-02', 7);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('paste', 'Sensitivity', 'tata_1mg', '2026-02-28', '2026-02', 6);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('paste', 'Sensitivity', 'zepto', '2026-02-28', '2026-02', 8);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('paste', 'Sensitivity', 'amazon_pharmacy', '2026-02-28', '2026-02', NULL);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('paste', 'Sensodyne', 'pharmeasy', '2026-02-28', '2026-02', 4);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('paste', 'Sensodyne', 'tata_1mg', '2026-02-28', '2026-02', 9);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('paste', 'Sensodyne', 'zepto', '2026-02-28', '2026-02', 7);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('paste', 'Sensodyne', 'amazon_pharmacy', '2026-02-28', '2026-02', 6);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('paste', 'Toothpaste', 'pharmeasy', '2026-02-28', '2026-02', 6);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('paste', 'Toothpaste', 'tata_1mg', '2026-02-28', '2026-02', 6);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('paste', 'Toothpaste', 'zepto', '2026-02-28', '2026-02', 7);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('paste', 'Toothpaste', 'amazon_pharmacy', '2026-02-28', '2026-02', 2);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('parodontax', 'Gum care', 'pharmeasy', '2026-02-28', '2026-02', 5);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('parodontax', 'Gum care', 'tata_1mg', '2026-02-28', '2026-02', 12);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('parodontax', 'Gum care', 'zepto', '2026-02-28', '2026-02', 16);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('parodontax', 'Gum care', 'amazon_pharmacy', '2026-02-28', '2026-02', 5);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('parodontax', 'Paste', 'pharmeasy', '2026-02-28', '2026-02', 7);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('parodontax', 'Paste', 'tata_1mg', '2026-02-28', '2026-02', 12);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('parodontax', 'Paste', 'zepto', '2026-02-28', '2026-02', 15);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('parodontax', 'Paste', 'amazon_pharmacy', '2026-02-28', '2026-02', 9);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('parodontax', 'Toothpaste', 'pharmeasy', '2026-02-28', '2026-02', 8);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('parodontax', 'Toothpaste', 'tata_1mg', '2026-02-28', '2026-02', 9);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('parodontax', 'Toothpaste', 'zepto', '2026-02-28', '2026-02', 15);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('parodontax', 'Toothpaste', 'amazon_pharmacy', '2026-02-28', '2026-02', 6);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('pronamel', 'paste', 'pharmeasy', '2026-02-28', '2026-02', 8);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('pronamel', 'paste', 'tata_1mg', '2026-02-28', '2026-02', 13);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('pronamel', 'paste', 'zepto', '2026-02-28', '2026-02', 16);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('pronamel', 'paste', 'amazon_pharmacy', '2026-02-28', '2026-02', 4);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('pronamel', 'pronamel', 'pharmeasy', '2026-02-28', '2026-02', 7);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('pronamel', 'pronamel', 'tata_1mg', '2026-02-28', '2026-02', 11);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('pronamel', 'pronamel', 'zepto', '2026-02-28', '2026-02', 15);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('pronamel', 'pronamel', 'amazon_pharmacy', '2026-02-28', '2026-02', 5);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('pronamel', 'sensitivity', 'pharmeasy', '2026-02-28', '2026-02', 7);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('pronamel', 'sensitivity', 'tata_1mg', '2026-02-28', '2026-02', 9);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('pronamel', 'sensitivity', 'zepto', '2026-02-28', '2026-02', 17);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('pronamel', 'sensitivity', 'amazon_pharmacy', '2026-02-28', '2026-02', NULL);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('pronamel', 'sensodyne', 'pharmeasy', '2026-02-28', '2026-02', 9);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('pronamel', 'sensodyne', 'tata_1mg', '2026-02-28', '2026-02', 13);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('pronamel', 'sensodyne', 'zepto', '2026-02-28', '2026-02', 15);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('pronamel', 'sensodyne', 'amazon_pharmacy', '2026-02-28', '2026-02', 8);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('pronamel', 'toothpaste', 'pharmeasy', '2026-02-28', '2026-02', 6);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('pronamel', 'toothpaste', 'tata_1mg', '2026-02-28', '2026-02', 11);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('pronamel', 'toothpaste', 'zepto', '2026-02-28', '2026-02', 18);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('pronamel', 'toothpaste', 'amazon_pharmacy', '2026-02-28', '2026-02', 8);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('mouthwash', 'Listerine', 'pharmeasy', '2026-02-28', '2026-02', 6);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('mouthwash', 'Listerine', 'tata_1mg', '2026-02-28', '2026-02', 13);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('mouthwash', 'Listerine', 'zepto', '2026-02-28', '2026-02', 18);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('mouthwash', 'Listerine', 'amazon_pharmacy', '2026-02-28', '2026-02', 9);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('mouthwash', 'Mouthwash', 'pharmeasy', '2026-02-28', '2026-02', 8);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('mouthwash', 'Mouthwash', 'tata_1mg', '2026-02-28', '2026-02', 15);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('mouthwash', 'Mouthwash', 'zepto', '2026-02-28', '2026-02', 21);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('mouthwash', 'Mouthwash', 'amazon_pharmacy', '2026-02-28', '2026-02', 6);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('mouthwash', 'sensodyne', 'pharmeasy', '2026-02-28', '2026-02', 8);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('mouthwash', 'sensodyne', 'tata_1mg', '2026-02-28', '2026-02', 14);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('mouthwash', 'sensodyne', 'zepto', '2026-02-28', '2026-02', 20);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('mouthwash', 'sensodyne', 'amazon_pharmacy', '2026-02-28', '2026-02', 7);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('mouthwash', 'sensodyne mouthwash', 'pharmeasy', '2026-02-28', '2026-02', 7);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('mouthwash', 'sensodyne mouthwash', 'tata_1mg', '2026-02-28', '2026-02', 14);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('mouthwash', 'sensodyne mouthwash', 'zepto', '2026-02-28', '2026-02', 21);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('mouthwash', 'sensodyne mouthwash', 'amazon_pharmacy', '2026-02-28', '2026-02', 6);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('polident', 'polident', 'pharmeasy', '2026-02-28', '2026-02', NULL);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('polident', 'polident', 'tata_1mg', '2026-02-28', '2026-02', 16);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('polident', 'polident', 'zepto', '2026-02-28', '2026-02', 22);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('polident', 'polident', 'amazon_pharmacy', '2026-02-28', '2026-02', 9);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('polident', 'denture adhesive', 'pharmeasy', '2026-02-28', '2026-02', 9);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('polident', 'denture adhesive', 'tata_1mg', '2026-02-28', '2026-02', 14);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('polident', 'denture adhesive', 'zepto', '2026-02-28', '2026-02', 23);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('polident', 'denture adhesive', 'amazon_pharmacy', '2026-02-28', '2026-02', 9);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('polident', 'denture fixative cream', 'pharmeasy', '2026-02-28', '2026-02', 9);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('polident', 'denture fixative cream', 'tata_1mg', '2026-02-28', '2026-02', 16);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('polident', 'denture fixative cream', 'zepto', '2026-02-28', '2026-02', 23);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('polident', 'denture fixative cream', 'amazon_pharmacy', '2026-02-28', '2026-02', 9);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('crocin', 'Dolo', 'pharmeasy', '2026-02-28', '2026-02', 3);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('crocin', 'Dolo', 'tata_1mg', '2026-02-28', '2026-02', 3);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('crocin', 'Dolo', 'zepto', '2026-02-28', '2026-02', 7);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('crocin', 'Dolo', 'amazon_pharmacy', '2026-02-28', '2026-02', 5);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('crocin', 'Pain Killer', 'pharmeasy', '2026-02-28', '2026-02', NULL);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('crocin', 'Pain Killer', 'tata_1mg', '2026-02-28', '2026-02', 4);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('crocin', 'Pain Killer', 'zepto', '2026-02-28', '2026-02', 7);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('crocin', 'Pain Killer', 'amazon_pharmacy', '2026-02-28', '2026-02', 6);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('crocin', 'Pain Relief', 'pharmeasy', '2026-02-28', '2026-02', 6);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('crocin', 'Pain Relief', 'tata_1mg', '2026-02-28', '2026-02', 5);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('crocin', 'Pain Relief', 'zepto', '2026-02-28', '2026-02', NULL);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('crocin', 'Pain Relief', 'amazon_pharmacy', '2026-02-28', '2026-02', NULL);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('crocin', 'Paracetamol', 'pharmeasy', '2026-02-28', '2026-02', 5);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('crocin', 'Paracetamol', 'tata_1mg', '2026-02-28', '2026-02', 3);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('crocin', 'Paracetamol', 'zepto', '2026-02-28', '2026-02', 7);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('crocin', 'Paracetamol', 'amazon_pharmacy', '2026-02-28', '2026-02', 5);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('crocin', 'cough syrup', 'pharmeasy', '2026-02-28', '2026-02', 5);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('crocin', 'cough syrup', 'tata_1mg', '2026-02-28', '2026-02', 7);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('crocin', 'cough syrup', 'zepto', '2026-02-28', '2026-02', 7);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('crocin', 'cough syrup', 'amazon_pharmacy', '2026-02-28', '2026-02', 6);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('iodex', 'Balm', 'pharmeasy', '2026-02-28', '2026-02', 7);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('iodex', 'Balm', 'tata_1mg', '2026-02-28', '2026-02', 11);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('iodex', 'Balm', 'zepto', '2026-02-28', '2026-02', 11);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('iodex', 'Balm', 'amazon_pharmacy', '2026-02-28', '2026-02', 3);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('iodex', 'Pain relief', 'pharmeasy', '2026-02-28', '2026-02', 7);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('iodex', 'Pain relief', 'tata_1mg', '2026-02-28', '2026-02', 10);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('iodex', 'Pain relief', 'zepto', '2026-02-28', '2026-02', 13);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('iodex', 'Pain relief', 'amazon_pharmacy', '2026-02-28', '2026-02', 6);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('iodex', 'Relief Spray', 'pharmeasy', '2026-02-28', '2026-02', 5);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('iodex', 'Relief Spray', 'tata_1mg', '2026-02-28', '2026-02', 9);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('iodex', 'Relief Spray', 'zepto', '2026-02-28', '2026-02', 12);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('iodex', 'Relief Spray', 'amazon_pharmacy', '2026-02-28', '2026-02', 7);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('voltaren', 'pain relief', 'pharmeasy', '2026-02-28', '2026-02', 11);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('voltaren', 'pain relief', 'tata_1mg', '2026-02-28', '2026-02', 16);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('voltaren', 'pain relief', 'zepto', '2026-02-28', '2026-02', 20);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('voltaren', 'pain relief', 'amazon_pharmacy', '2026-02-28', '2026-02', 11);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('centrum', 'Bone Health', 'pharmeasy', '2026-02-28', '2026-02', 4);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('centrum', 'Bone Health', 'tata_1mg', '2026-02-28', '2026-02', 7);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('centrum', 'Bone Health', 'zepto', '2026-02-28', '2026-02', 8);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('centrum', 'Bone Health', 'amazon_pharmacy', '2026-02-28', '2026-02', 4);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('centrum', 'Multivitamin', 'pharmeasy', '2026-02-28', '2026-02', 4);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('centrum', 'Multivitamin', 'tata_1mg', '2026-02-28', '2026-02', 8);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('centrum', 'Multivitamin', 'zepto', '2026-02-28', '2026-02', 12);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('centrum', 'Multivitamin', 'amazon_pharmacy', '2026-02-28', '2026-02', 6);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('centrum', 'Recharge', 'pharmeasy', '2026-02-28', '2026-02', 7);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('centrum', 'Recharge', 'tata_1mg', '2026-02-28', '2026-02', 7);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('centrum', 'Recharge', 'zepto', '2026-02-28', '2026-02', 10);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('centrum', 'Recharge', 'amazon_pharmacy', '2026-02-28', '2026-02', 4);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('centrum', 'Vitamins', 'pharmeasy', '2026-02-28', '2026-02', 7);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('centrum', 'Vitamins', 'tata_1mg', '2026-02-28', '2026-02', 5);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('centrum', 'Vitamins', 'zepto', '2026-02-28', '2026-02', 11);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('centrum', 'Vitamins', 'amazon_pharmacy', '2026-02-28', '2026-02', 7);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('centrum', 'calcium', 'pharmeasy', '2026-02-28', '2026-02', 7);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('centrum', 'calcium', 'tata_1mg', '2026-02-28', '2026-02', 4);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('centrum', 'calcium', 'zepto', '2026-02-28', '2026-02', 10);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('centrum', 'calcium', 'amazon_pharmacy', '2026-02-28', '2026-02', 4);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('ostocalcium', 'Health supplement', 'pharmeasy', '2026-02-28', '2026-02', 9);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('ostocalcium', 'Health supplement', 'tata_1mg', '2026-02-28', '2026-02', 9);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('ostocalcium', 'Health supplement', 'zepto', '2026-02-28', '2026-02', 18);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('ostocalcium', 'Health supplement', 'amazon_pharmacy', '2026-02-28', '2026-02', 7);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('ostocalcium', 'Multivitamin', 'pharmeasy', '2026-02-28', '2026-02', 8);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('ostocalcium', 'Multivitamin', 'tata_1mg', '2026-02-28', '2026-02', 9);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('ostocalcium', 'Multivitamin', 'zepto', '2026-02-28', '2026-02', 17);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('ostocalcium', 'Multivitamin', 'amazon_pharmacy', '2026-02-28', '2026-02', 8);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('ostocalcium', 'Vitamin D', 'pharmeasy', '2026-02-28', '2026-02', 5);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('ostocalcium', 'Vitamin D', 'tata_1mg', '2026-02-28', '2026-02', 12);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('ostocalcium', 'Vitamin D', 'zepto', '2026-02-28', '2026-02', 14);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('ostocalcium', 'Vitamin D', 'amazon_pharmacy', '2026-02-28', '2026-02', 6);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('ostocalcium', 'calcium', 'pharmeasy', '2026-02-28', '2026-02', 5);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('ostocalcium', 'calcium', 'tata_1mg', '2026-02-28', '2026-02', 13);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('ostocalcium', 'calcium', 'zepto', '2026-02-28', '2026-02', 14);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('ostocalcium', 'calcium', 'amazon_pharmacy', '2026-02-28', '2026-02', 6);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('ostocalcium', 'vitamins', 'pharmeasy', '2026-02-28', '2026-02', 8);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('ostocalcium', 'vitamins', 'tata_1mg', '2026-02-28', '2026-02', 13);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('ostocalcium', 'vitamins', 'zepto', '2026-02-28', '2026-02', 18);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('ostocalcium', 'vitamins', 'amazon_pharmacy', '2026-02-28', '2026-02', 9);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('eno', 'Acidity', 'pharmeasy', '2026-02-28', '2026-02', 6);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('eno', 'Acidity', 'tata_1mg', '2026-02-28', '2026-02', 5);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('eno', 'Acidity', 'zepto', '2026-02-28', '2026-02', 4);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('eno', 'Acidity', 'amazon_pharmacy', '2026-02-28', '2026-02', 2);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('eno', 'Antacid', 'pharmeasy', '2026-02-28', '2026-02', 3);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('eno', 'Antacid', 'tata_1mg', '2026-02-28', '2026-02', 5);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('eno', 'Antacid', 'zepto', '2026-02-28', '2026-02', 5);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('eno', 'Antacid', 'amazon_pharmacy', '2026-02-28', '2026-02', NULL);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('eno', 'Digestion', 'pharmeasy', '2026-02-28', '2026-02', 2);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('eno', 'Digestion', 'tata_1mg', '2026-02-28', '2026-02', 7);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('eno', 'Digestion', 'zepto', '2026-02-28', '2026-02', 4);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('eno', 'Digestion', 'amazon_pharmacy', '2026-02-28', '2026-02', 4);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('eno', 'Eno', 'pharmeasy', '2026-02-28', '2026-02', NULL);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('eno', 'Eno', 'tata_1mg', '2026-02-28', '2026-02', 4);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('eno', 'Eno', 'zepto', '2026-02-28', '2026-02', 8);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('eno', 'Eno', 'amazon_pharmacy', '2026-02-28', '2026-02', 3);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('eno', 'Indigestion', 'pharmeasy', '2026-02-28', '2026-02', 6);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('eno', 'Indigestion', 'tata_1mg', '2026-02-28', '2026-02', 4);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('eno', 'Indigestion', 'zepto', '2026-02-28', '2026-02', NULL);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('eno', 'Indigestion', 'amazon_pharmacy', '2026-02-28', '2026-02', 3);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('otrivin', 'blocked nose', 'pharmeasy', '2026-02-28', '2026-02', 8);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('otrivin', 'blocked nose', 'tata_1mg', '2026-02-28', '2026-02', 10);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('otrivin', 'blocked nose', 'zepto', '2026-02-28', '2026-02', 12);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('otrivin', 'blocked nose', 'amazon_pharmacy', '2026-02-28', '2026-02', 7);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('otrivin', 'nasal spray', 'pharmeasy', '2026-02-28', '2026-02', 6);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('otrivin', 'nasal spray', 'tata_1mg', '2026-02-28', '2026-02', 9);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('otrivin', 'nasal spray', 'zepto', '2026-02-28', '2026-02', NULL);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('otrivin', 'nasal spray', 'amazon_pharmacy', '2026-02-28', '2026-02', 8);

-- 2026-03
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('brush', 'Brush', 'pharmeasy', '2026-03-31', '2026-03', 5);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('brush', 'Brush', 'tata_1mg', '2026-03-31', '2026-03', 31);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('brush', 'Brush', 'zepto', '2026-03-31', '2026-03', 7);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('brush', 'Brush', 'amazon_pharmacy', '2026-03-31', '2026-03', 1);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('brush', 'Gentle brush', 'pharmeasy', '2026-03-31', '2026-03', 3);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('brush', 'Gentle brush', 'tata_1mg', '2026-03-31', '2026-03', 32);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('brush', 'Gentle brush', 'zepto', '2026-03-31', '2026-03', 6);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('brush', 'Gentle brush', 'amazon_pharmacy', '2026-03-31', '2026-03', 1);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('brush', 'Sensodyne', 'pharmeasy', '2026-03-31', '2026-03', 4);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('brush', 'Sensodyne', 'tata_1mg', '2026-03-31', '2026-03', 34);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('brush', 'Sensodyne', 'zepto', '2026-03-31', '2026-03', 6);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('brush', 'Sensodyne', 'amazon_pharmacy', '2026-03-31', '2026-03', 2);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('brush', 'Toothbrush', 'pharmeasy', '2026-03-31', '2026-03', 1);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('brush', 'Toothbrush', 'tata_1mg', '2026-03-31', '2026-03', 33);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('brush', 'Toothbrush', 'zepto', '2026-03-31', '2026-03', 6);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('brush', 'Toothbrush', 'amazon_pharmacy', '2026-03-31', '2026-03', 3);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('brush', 'sensitivity', 'pharmeasy', '2026-03-31', '2026-03', NULL);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('brush', 'sensitivity', 'tata_1mg', '2026-03-31', '2026-03', 31);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('brush', 'sensitivity', 'zepto', '2026-03-31', '2026-03', 5);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('brush', 'sensitivity', 'amazon_pharmacy', '2026-03-31', '2026-03', 3);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('paste', 'Paste', 'pharmeasy', '2026-03-31', '2026-03', 2);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('paste', 'Paste', 'tata_1mg', '2026-03-31', '2026-03', 8);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('paste', 'Paste', 'zepto', '2026-03-31', '2026-03', 6);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('paste', 'Paste', 'amazon_pharmacy', '2026-03-31', '2026-03', 3);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('paste', 'Sensitivity', 'pharmeasy', '2026-03-31', '2026-03', 5);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('paste', 'Sensitivity', 'tata_1mg', '2026-03-31', '2026-03', 4);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('paste', 'Sensitivity', 'zepto', '2026-03-31', '2026-03', 10);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('paste', 'Sensitivity', 'amazon_pharmacy', '2026-03-31', '2026-03', 3);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('paste', 'Sensodyne', 'pharmeasy', '2026-03-31', '2026-03', 5);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('paste', 'Sensodyne', 'tata_1mg', '2026-03-31', '2026-03', 8);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('paste', 'Sensodyne', 'zepto', '2026-03-31', '2026-03', 7);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('paste', 'Sensodyne', 'amazon_pharmacy', '2026-03-31', '2026-03', 1);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('paste', 'Toothpaste', 'pharmeasy', '2026-03-31', '2026-03', 2);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('paste', 'Toothpaste', 'tata_1mg', '2026-03-31', '2026-03', 4);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('paste', 'Toothpaste', 'zepto', '2026-03-31', '2026-03', 6);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('paste', 'Toothpaste', 'amazon_pharmacy', '2026-03-31', '2026-03', 2);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('parodontax', 'Gum care', 'pharmeasy', '2026-03-31', '2026-03', 5);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('parodontax', 'Gum care', 'tata_1mg', '2026-03-31', '2026-03', 9);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('parodontax', 'Gum care', 'zepto', '2026-03-31', '2026-03', 14);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('parodontax', 'Gum care', 'amazon_pharmacy', '2026-03-31', '2026-03', 5);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('parodontax', 'Paste', 'pharmeasy', '2026-03-31', '2026-03', 4);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('parodontax', 'Paste', 'tata_1mg', '2026-03-31', '2026-03', 11);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('parodontax', 'Paste', 'zepto', '2026-03-31', '2026-03', 12);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('parodontax', 'Paste', 'amazon_pharmacy', '2026-03-31', '2026-03', 6);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('parodontax', 'Toothpaste', 'pharmeasy', '2026-03-31', '2026-03', 6);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('parodontax', 'Toothpaste', 'tata_1mg', '2026-03-31', '2026-03', 11);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('parodontax', 'Toothpaste', 'zepto', '2026-03-31', '2026-03', 11);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('parodontax', 'Toothpaste', 'amazon_pharmacy', '2026-03-31', '2026-03', 6);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('pronamel', 'paste', 'pharmeasy', '2026-03-31', '2026-03', 9);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('pronamel', 'paste', 'tata_1mg', '2026-03-31', '2026-03', 11);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('pronamel', 'paste', 'zepto', '2026-03-31', '2026-03', 17);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('pronamel', 'paste', 'amazon_pharmacy', '2026-03-31', '2026-03', 5);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('pronamel', 'pronamel', 'pharmeasy', '2026-03-31', '2026-03', 9);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('pronamel', 'pronamel', 'tata_1mg', '2026-03-31', '2026-03', 10);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('pronamel', 'pronamel', 'zepto', '2026-03-31', '2026-03', 15);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('pronamel', 'pronamel', 'amazon_pharmacy', '2026-03-31', '2026-03', 4);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('pronamel', 'sensitivity', 'pharmeasy', '2026-03-31', '2026-03', NULL);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('pronamel', 'sensitivity', 'tata_1mg', '2026-03-31', '2026-03', 11);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('pronamel', 'sensitivity', 'zepto', '2026-03-31', '2026-03', 17);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('pronamel', 'sensitivity', 'amazon_pharmacy', '2026-03-31', '2026-03', 4);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('pronamel', 'sensodyne', 'pharmeasy', '2026-03-31', '2026-03', 5);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('pronamel', 'sensodyne', 'tata_1mg', '2026-03-31', '2026-03', 12);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('pronamel', 'sensodyne', 'zepto', '2026-03-31', '2026-03', 14);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('pronamel', 'sensodyne', 'amazon_pharmacy', '2026-03-31', '2026-03', 6);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('pronamel', 'toothpaste', 'pharmeasy', '2026-03-31', '2026-03', NULL);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('pronamel', 'toothpaste', 'tata_1mg', '2026-03-31', '2026-03', 9);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('pronamel', 'toothpaste', 'zepto', '2026-03-31', '2026-03', NULL);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('pronamel', 'toothpaste', 'amazon_pharmacy', '2026-03-31', '2026-03', 5);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('mouthwash', 'Listerine', 'pharmeasy', '2026-03-31', '2026-03', 7);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('mouthwash', 'Listerine', 'tata_1mg', '2026-03-31', '2026-03', 12);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('mouthwash', 'Listerine', 'zepto', '2026-03-31', '2026-03', 21);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('mouthwash', 'Listerine', 'amazon_pharmacy', '2026-03-31', '2026-03', 7);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('mouthwash', 'Mouthwash', 'pharmeasy', '2026-03-31', '2026-03', 7);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('mouthwash', 'Mouthwash', 'tata_1mg', '2026-03-31', '2026-03', 10);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('mouthwash', 'Mouthwash', 'zepto', '2026-03-31', '2026-03', 18);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('mouthwash', 'Mouthwash', 'amazon_pharmacy', '2026-03-31', '2026-03', 7);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('mouthwash', 'sensodyne', 'pharmeasy', '2026-03-31', '2026-03', 4);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('mouthwash', 'sensodyne', 'tata_1mg', '2026-03-31', '2026-03', 10);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('mouthwash', 'sensodyne', 'zepto', '2026-03-31', '2026-03', 17);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('mouthwash', 'sensodyne', 'amazon_pharmacy', '2026-03-31', '2026-03', 7);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('mouthwash', 'sensodyne mouthwash', 'pharmeasy', '2026-03-31', '2026-03', 4);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('mouthwash', 'sensodyne mouthwash', 'tata_1mg', '2026-03-31', '2026-03', 10);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('mouthwash', 'sensodyne mouthwash', 'zepto', '2026-03-31', '2026-03', 19);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('mouthwash', 'sensodyne mouthwash', 'amazon_pharmacy', '2026-03-31', '2026-03', 6);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('polident', 'polident', 'pharmeasy', '2026-03-31', '2026-03', 11);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('polident', 'polident', 'tata_1mg', '2026-03-31', '2026-03', 14);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('polident', 'polident', 'zepto', '2026-03-31', '2026-03', 21);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('polident', 'polident', 'amazon_pharmacy', '2026-03-31', '2026-03', 11);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('polident', 'denture adhesive', 'pharmeasy', '2026-03-31', '2026-03', 8);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('polident', 'denture adhesive', 'tata_1mg', '2026-03-31', '2026-03', 17);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('polident', 'denture adhesive', 'zepto', '2026-03-31', '2026-03', 24);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('polident', 'denture adhesive', 'amazon_pharmacy', '2026-03-31', '2026-03', 11);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('polident', 'denture fixative cream', 'pharmeasy', '2026-03-31', '2026-03', 7);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('polident', 'denture fixative cream', 'tata_1mg', '2026-03-31', '2026-03', 16);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('polident', 'denture fixative cream', 'zepto', '2026-03-31', '2026-03', 25);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('polident', 'denture fixative cream', 'amazon_pharmacy', '2026-03-31', '2026-03', 11);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('crocin', 'Dolo', 'pharmeasy', '2026-03-31', '2026-03', 5);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('crocin', 'Dolo', 'tata_1mg', '2026-03-31', '2026-03', 5);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('crocin', 'Dolo', 'zepto', '2026-03-31', '2026-03', 7);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('crocin', 'Dolo', 'amazon_pharmacy', '2026-03-31', '2026-03', 2);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('crocin', 'Pain Killer', 'pharmeasy', '2026-03-31', '2026-03', 4);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('crocin', 'Pain Killer', 'tata_1mg', '2026-03-31', '2026-03', 5);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('crocin', 'Pain Killer', 'zepto', '2026-03-31', '2026-03', 8);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('crocin', 'Pain Killer', 'amazon_pharmacy', '2026-03-31', '2026-03', NULL);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('crocin', 'Pain Relief', 'pharmeasy', '2026-03-31', '2026-03', 4);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('crocin', 'Pain Relief', 'tata_1mg', '2026-03-31', '2026-03', 6);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('crocin', 'Pain Relief', 'zepto', '2026-03-31', '2026-03', 4);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('crocin', 'Pain Relief', 'amazon_pharmacy', '2026-03-31', '2026-03', 4);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('crocin', 'Paracetamol', 'pharmeasy', '2026-03-31', '2026-03', 3);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('crocin', 'Paracetamol', 'tata_1mg', '2026-03-31', '2026-03', 3);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('crocin', 'Paracetamol', 'zepto', '2026-03-31', '2026-03', 6);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('crocin', 'Paracetamol', 'amazon_pharmacy', '2026-03-31', '2026-03', 2);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('crocin', 'cough syrup', 'pharmeasy', '2026-03-31', '2026-03', 2);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('crocin', 'cough syrup', 'tata_1mg', '2026-03-31', '2026-03', 2);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('crocin', 'cough syrup', 'zepto', '2026-03-31', '2026-03', NULL);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('crocin', 'cough syrup', 'amazon_pharmacy', '2026-03-31', '2026-03', 3);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('iodex', 'Balm', 'pharmeasy', '2026-03-31', '2026-03', 3);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('iodex', 'Balm', 'tata_1mg', '2026-03-31', '2026-03', 8);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('iodex', 'Balm', 'zepto', '2026-03-31', '2026-03', 10);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('iodex', 'Balm', 'amazon_pharmacy', '2026-03-31', '2026-03', 6);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('iodex', 'Pain relief', 'pharmeasy', '2026-03-31', '2026-03', 5);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('iodex', 'Pain relief', 'tata_1mg', '2026-03-31', '2026-03', 8);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('iodex', 'Pain relief', 'zepto', '2026-03-31', '2026-03', 11);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('iodex', 'Pain relief', 'amazon_pharmacy', '2026-03-31', '2026-03', 5);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('iodex', 'Relief Spray', 'pharmeasy', '2026-03-31', '2026-03', 5);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('iodex', 'Relief Spray', 'tata_1mg', '2026-03-31', '2026-03', 8);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('iodex', 'Relief Spray', 'zepto', '2026-03-31', '2026-03', 12);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('iodex', 'Relief Spray', 'amazon_pharmacy', '2026-03-31', '2026-03', 3);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('voltaren', 'pain relief', 'pharmeasy', '2026-03-31', '2026-03', 9);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('voltaren', 'pain relief', 'tata_1mg', '2026-03-31', '2026-03', 14);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('voltaren', 'pain relief', 'zepto', '2026-03-31', '2026-03', 23);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('voltaren', 'pain relief', 'amazon_pharmacy', '2026-03-31', '2026-03', NULL);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('centrum', 'Bone Health', 'pharmeasy', '2026-03-31', '2026-03', 6);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('centrum', 'Bone Health', 'tata_1mg', '2026-03-31', '2026-03', 5);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('centrum', 'Bone Health', 'zepto', '2026-03-31', '2026-03', 9);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('centrum', 'Bone Health', 'amazon_pharmacy', '2026-03-31', '2026-03', 4);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('centrum', 'Multivitamin', 'pharmeasy', '2026-03-31', '2026-03', 3);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('centrum', 'Multivitamin', 'tata_1mg', '2026-03-31', '2026-03', 7);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('centrum', 'Multivitamin', 'zepto', '2026-03-31', '2026-03', 11);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('centrum', 'Multivitamin', 'amazon_pharmacy', '2026-03-31', '2026-03', 6);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('centrum', 'Recharge', 'pharmeasy', '2026-03-31', '2026-03', 2);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('centrum', 'Recharge', 'tata_1mg', '2026-03-31', '2026-03', 6);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('centrum', 'Recharge', 'zepto', '2026-03-31', '2026-03', 9);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('centrum', 'Recharge', 'amazon_pharmacy', '2026-03-31', '2026-03', 2);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('centrum', 'Vitamins', 'pharmeasy', '2026-03-31', '2026-03', 2);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('centrum', 'Vitamins', 'tata_1mg', '2026-03-31', '2026-03', 6);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('centrum', 'Vitamins', 'zepto', '2026-03-31', '2026-03', 8);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('centrum', 'Vitamins', 'amazon_pharmacy', '2026-03-31', '2026-03', 3);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('centrum', 'calcium', 'pharmeasy', '2026-03-31', '2026-03', 4);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('centrum', 'calcium', 'tata_1mg', '2026-03-31', '2026-03', 7);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('centrum', 'calcium', 'zepto', '2026-03-31', '2026-03', 8);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('centrum', 'calcium', 'amazon_pharmacy', '2026-03-31', '2026-03', 2);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('ostocalcium', 'Health supplement', 'pharmeasy', '2026-03-31', '2026-03', 8);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('ostocalcium', 'Health supplement', 'tata_1mg', '2026-03-31', '2026-03', NULL);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('ostocalcium', 'Health supplement', 'zepto', '2026-03-31', '2026-03', 15);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('ostocalcium', 'Health supplement', 'amazon_pharmacy', '2026-03-31', '2026-03', 8);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('ostocalcium', 'Multivitamin', 'pharmeasy', '2026-03-31', '2026-03', 6);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('ostocalcium', 'Multivitamin', 'tata_1mg', '2026-03-31', '2026-03', 10);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('ostocalcium', 'Multivitamin', 'zepto', '2026-03-31', '2026-03', NULL);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('ostocalcium', 'Multivitamin', 'amazon_pharmacy', '2026-03-31', '2026-03', 7);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('ostocalcium', 'Vitamin D', 'pharmeasy', '2026-03-31', '2026-03', 4);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('ostocalcium', 'Vitamin D', 'tata_1mg', '2026-03-31', '2026-03', 11);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('ostocalcium', 'Vitamin D', 'zepto', '2026-03-31', '2026-03', 14);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('ostocalcium', 'Vitamin D', 'amazon_pharmacy', '2026-03-31', '2026-03', 9);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('ostocalcium', 'calcium', 'pharmeasy', '2026-03-31', '2026-03', 4);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('ostocalcium', 'calcium', 'tata_1mg', '2026-03-31', '2026-03', 9);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('ostocalcium', 'calcium', 'zepto', '2026-03-31', '2026-03', 17);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('ostocalcium', 'calcium', 'amazon_pharmacy', '2026-03-31', '2026-03', 9);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('ostocalcium', 'vitamins', 'pharmeasy', '2026-03-31', '2026-03', 5);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('ostocalcium', 'vitamins', 'tata_1mg', '2026-03-31', '2026-03', 9);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('ostocalcium', 'vitamins', 'zepto', '2026-03-31', '2026-03', 14);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('ostocalcium', 'vitamins', 'amazon_pharmacy', '2026-03-31', '2026-03', NULL);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('eno', 'Acidity', 'pharmeasy', '2026-03-31', '2026-03', 2);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('eno', 'Acidity', 'tata_1mg', '2026-03-31', '2026-03', 6);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('eno', 'Acidity', 'zepto', '2026-03-31', '2026-03', 4);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('eno', 'Acidity', 'amazon_pharmacy', '2026-03-31', '2026-03', 1);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('eno', 'Antacid', 'pharmeasy', '2026-03-31', '2026-03', 3);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('eno', 'Antacid', 'tata_1mg', '2026-03-31', '2026-03', 3);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('eno', 'Antacid', 'zepto', '2026-03-31', '2026-03', 3);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('eno', 'Antacid', 'amazon_pharmacy', '2026-03-31', '2026-03', 1);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('eno', 'Digestion', 'pharmeasy', '2026-03-31', '2026-03', 4);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('eno', 'Digestion', 'tata_1mg', '2026-03-31', '2026-03', 2);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('eno', 'Digestion', 'zepto', '2026-03-31', '2026-03', 5);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('eno', 'Digestion', 'amazon_pharmacy', '2026-03-31', '2026-03', 1);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('eno', 'Eno', 'pharmeasy', '2026-03-31', '2026-03', 2);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('eno', 'Eno', 'tata_1mg', '2026-03-31', '2026-03', 2);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('eno', 'Eno', 'zepto', '2026-03-31', '2026-03', 7);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('eno', 'Eno', 'amazon_pharmacy', '2026-03-31', '2026-03', NULL);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('eno', 'Indigestion', 'pharmeasy', '2026-03-31', '2026-03', 4);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('eno', 'Indigestion', 'tata_1mg', '2026-03-31', '2026-03', 5);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('eno', 'Indigestion', 'zepto', '2026-03-31', '2026-03', 6);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('eno', 'Indigestion', 'amazon_pharmacy', '2026-03-31', '2026-03', NULL);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('otrivin', 'blocked nose', 'pharmeasy', '2026-03-31', '2026-03', 3);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('otrivin', 'blocked nose', 'tata_1mg', '2026-03-31', '2026-03', NULL);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('otrivin', 'blocked nose', 'zepto', '2026-03-31', '2026-03', 10);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('otrivin', 'blocked nose', 'amazon_pharmacy', '2026-03-31', '2026-03', 8);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('otrivin', 'nasal spray', 'pharmeasy', '2026-03-31', '2026-03', 5);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('otrivin', 'nasal spray', 'tata_1mg', '2026-03-31', '2026-03', 9);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('otrivin', 'nasal spray', 'zepto', '2026-03-31', '2026-03', 11);
INSERT OR IGNORE INTO visibility (brand_id, keyword, platform, week_ending, period, rank) VALUES ('otrivin', 'nasal spray', 'amazon_pharmacy', '2026-03-31', '2026-03', 7);

