/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VisibilityRouteImport } from './routes/visibility'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as SnapshotRouteImport } from './routes/snapshot'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PurchaseOrdersRouteImport } from './routes/purchase-orders'
import { Route as OfftakesRouteImport } from './routes/offtakes'
import { Route as MarketShareRouteImport } from './routes/market-share'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ListingsRouteImport } from './routes/listings'
import { Route as DigitalSpendsRouteImport } from './routes/digital-spends'
import { Route as BrandHealthRouteImport } from './routes/brand-health'
import { Route as IndexRouteImport } from './routes/index'

const VisibilityRoute = VisibilityRouteImport.update({
  id: '/visibility',
  path: '/visibility',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const SnapshotRoute = SnapshotRouteImport.update({
  id: '/snapshot',
  path: '/snapshot',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchaseOrdersRoute = PurchaseOrdersRouteImport.update({
  id: '/purchase-orders',
  path: '/purchase-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const OfftakesRoute = OfftakesRouteImport.update({
  id: '/offtakes',
  path: '/offtakes',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketShareRoute = MarketShareRouteImport.update({
  id: '/market-share',
  path: '/market-share',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingsRoute = ListingsRouteImport.update({
  id: '/listings',
  path: '/listings',
  getParentRoute: () => rootRouteImport,
} as any)
const DigitalSpendsRoute = DigitalSpendsRouteImport.update({
  id: '/digital-spends',
  path: '/digital-spends',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandHealthRoute = BrandHealthRouteImport.update({
  id: '/brand-health',
  path: '/brand-health',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/brand-health': typeof BrandHealthRoute
  '/digital-spends': typeof DigitalSpendsRoute
  '/listings': typeof ListingsRoute
  '/login': typeof LoginRoute
  '/market-share': typeof MarketShareRoute
  '/offtakes': typeof OfftakesRoute
  '/pricing': typeof PricingRoute
  '/purchase-orders': typeof PurchaseOrdersRoute
  '/snapshot': typeof SnapshotRoute
  '/upload': typeof UploadRoute
  '/visibility': typeof VisibilityRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/brand-health': typeof BrandHealthRoute
  '/digital-spends': typeof DigitalSpendsRoute
  '/listings': typeof ListingsRoute
  '/login': typeof LoginRoute
  '/market-share': typeof MarketShareRoute
  '/offtakes': typeof OfftakesRoute
  '/pricing': typeof PricingRoute
  '/purchase-orders': typeof PurchaseOrdersRoute
  '/snapshot': typeof SnapshotRoute
  '/upload': typeof UploadRoute
  '/visibility': typeof VisibilityRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/purchase-orders': typeof PurchaseOrdersRoute
  '/': typeof IndexRoute
  '/brand-health': typeof BrandHealthRoute
  '/digital-spends': typeof DigitalSpendsRoute
  '/listings': typeof ListingsRoute
  '/login': typeof LoginRoute
  '/market-share': typeof MarketShareRoute
  '/offtakes': typeof OfftakesRoute
  '/pricing': typeof PricingRoute
  '/snapshot': typeof SnapshotRoute
  '/upload': typeof UploadRoute
  '/visibility': typeof VisibilityRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/brand-health'
    | '/digital-spends'
    | '/listings'
    | '/login'
    | '/market-share'
    | '/offtakes'
    | '/pricing'
    | '/purchase-orders'
    | '/snapshot'
    | '/upload'
    | '/visibility'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/brand-health'
    | '/digital-spends'
    | '/listings'
    | '/login'
    | '/market-share'
    | '/offtakes'
    | '/pricing'
    | '/purchase-orders'
    | '/snapshot'
    | '/upload'
    | '/visibility'
  id:
    | '__root__'
    | '/'
    | '/brand-health'
    | '/digital-spends'
    | '/listings'
    | '/login'
    | '/market-share'
    | '/offtakes'
    | '/pricing'
    | '/purchase-orders'
    | '/snapshot'
    | '/upload'
    | '/visibility'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrandHealthRoute: typeof BrandHealthRoute
  DigitalSpendsRoute: typeof DigitalSpendsRoute
  ListingsRoute: typeof ListingsRoute
  LoginRoute: typeof LoginRoute
  MarketShareRoute: typeof MarketShareRoute
  OfftakesRoute: typeof OfftakesRoute
  PricingRoute: typeof PricingRoute
  PurchaseOrdersRoute: typeof PurchaseOrdersRoute
  SnapshotRoute: typeof SnapshotRoute
  UploadRoute: typeof UploadRoute
  VisibilityRoute: typeof VisibilityRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/visibility': {
      id: '/visibility'
      path: '/visibility'
      fullPath: '/visibility'
      preLoaderRoute: typeof VisibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/snapshot': {
      id: '/snapshot'
      path: '/snapshot'
      fullPath: '/snapshot'
      preLoaderRoute: typeof SnapshotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchase-orders': {
      id: '/purchase-orders'
      path: '/purchase-orders'
      fullPath: '/purchase-orders'
      preLoaderRoute: typeof PurchaseOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offtakes': {
      id: '/offtakes'
      path: '/offtakes'
      fullPath: '/offtakes'
      preLoaderRoute: typeof OfftakesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market-share': {
      id: '/market-share'
      path: '/market-share'
      fullPath: '/market-share'
      preLoaderRoute: typeof MarketShareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listings': {
      id: '/listings'
      path: '/listings'
      fullPath: '/listings'
      preLoaderRoute: typeof ListingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand-health': {
      id: '/brand-health'
      path: '/brand-health'
      fullPath: '/brand-health'
      preLoaderRoute: typeof BrandHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/digital-spends': {
      id: '/digital-spends'
      path: '/digital-spends'
      fullPath: '/digital-spends'
      preLoaderRoute: typeof DigitalSpendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrandHealthRoute: BrandHealthRoute,
  DigitalSpendsRoute: DigitalSpendsRoute,
  ListingsRoute: ListingsRoute,
  LoginRoute: LoginRoute,
  MarketShareRoute: MarketShareRoute,
  OfftakesRoute: OfftakesRoute,
  PricingRoute: PricingRoute,
  PurchaseOrdersRoute: PurchaseOrdersRoute,
  SnapshotRoute: SnapshotRoute,
  UploadRoute: UploadRoute,
  VisibilityRoute: VisibilityRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
